#!/usr/bin/python
import os
import sys
sys.path.append(os.path.expanduser('~/wordgames/python'))
from wsgiref.handlers import CGIHandler
#from words import Words

os.environ['D2DICT'] = os.path.expanduser('~/.local/share/moby')
os.environ['WORDSBIN'] = os.path.expanduser('~/wordgames')

from wordsapp import app

if 'GATEWAY_INTERFACE' in os.environ:
    from wsgirefhandlers import CGIHandler
    CGIHandler().run(app)
else:
    app.run(host='0.0.0.0', port=8080, threaded=True,
            debug=True)
#CGIHandler().run(app)
